version: '3.8'

services:
  # --- CÁC DỊCH VỤ BACKEND & FRONTEND ---
  frontend:
    build: ./DrugStoreWebsiteFE
    ports: ["4200:80"]
    networks: ["drugstore_network"]
    depends_on: ["authen-api", "data-api", "ai-service"]

  authen-api:
    build: ./DrugStoreWebsiteAuthen
    ports: ["5001:8080"]
    networks: ["drugstore_network"]
    env_file: ["./DrugStoreWebsiteAuthen/DrugStoreWebsiteAuthen.Api/.env"]
    extra_hosts: ["host.docker.internal:host-gateway"]

  data-api:
    build: ./DrugStoreWebsiteData
    ports: ["5002:8080"]
    networks: ["drugstore_network"]
    env_file: ["./DrugStoreWebsiteData/DrugStoreWebSiteData.Api/.env"]
    extra_hosts: ["host.docker.internal:host-gateway"]

  ai-service:
    build: ./DrugStoreWebsiteAI
    ports: ["8888:8888"]
    networks: ["drugstore_network"]
    env_file: ["./DrugStoreWebsiteAI/.env"]
    extra_hosts: ["host.docker.internal:host-gateway"]

  # --- HẠ TẦNG BỔ TRỢ ---
  redis-cache:
    image: redis:7.2-alpine
    container_name: drugstore-redis
    ports: ["6379:6379"]
    networks: ["drugstore_network"]
    volumes: ["redis_data:/data"]
    command: redis-server --appendonly yes

  minio-storage:
    image: minio/minio:latest
    container_name: drugstore-minio
    ports: ["9000:9000", "9001:9001"]
    environment:
      - MINIO_ROOT_USER=drugstoreadmin
      - MINIO_ROOT_PASSWORD=Votanhuy@123
    volumes: ["minio_data:/data"]
    networks: ["drugstore_network"]
    command: server /data --console-address ":9001"

networks:
  drugstore_network:
    driver: bridge

volumes:
  redis_data:
  minio_data: